<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822180806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE exercise (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(150) NOT NULL,
              abbreviation VARCHAR(20) DEFAULT NULL,
              difficulty VARCHAR(255) NOT NULL,
              role VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE exercise_skill (
              exercise_id INT NOT NULL,
              skill_id INT NOT NULL,
              PRIMARY KEY (exercise_id, skill_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7B0B13B5E934951A ON exercise_skill (exercise_id)');
        $this->addSql('CREATE INDEX IDX_7B0B13B55585C142 ON exercise_skill (skill_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE exercise_group (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(150) NOT NULL,
              description TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE exercise_group_item (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              position INT NOT NULL,
              group_id INT NOT NULL,
              exercise_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7630A20EFE54D947 ON exercise_group_item (group_id)');
        $this->addSql('CREATE INDEX IDX_7630A20EE934951A ON exercise_group_item (exercise_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE partnership (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              partner_alias VARCHAR(100) DEFAULT NULL,
              status VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user1_id INT NOT NULL,
              user2_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_8619D6AE56AE248B ON partnership (user1_id)');
        $this->addSql('CREATE INDEX IDX_8619D6AE441B8B65 ON partnership (user2_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE partnership_progress (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(255) NOT NULL,
              status VARCHAR(255) NOT NULL,
              mastered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              partnership_id INT NOT NULL,
              exercise_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DA7ABF1B6AE7F85 ON partnership_progress (partnership_id)');
        $this->addSql('CREATE INDEX IDX_DA7ABF1BE934951A ON partnership_progress (exercise_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_DA7ABF1B6AE7F85E934951A57698A6A ON partnership_progress (
              partnership_id, exercise_id, role
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE session_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              session_date DATE NOT NULL,
              notes TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              partnership_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_F2E6F0FF6AE7F85 ON session_log (partnership_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE skill (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(100) NOT NULL,
              abbreviation VARCHAR(20) DEFAULT NULL,
              category VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              display_name VARCHAR(100) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE user_exercise_progress (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(255) NOT NULL,
              status VARCHAR(255) NOT NULL,
              mastered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              exercise_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DC72E985A76ED395 ON user_exercise_progress (user_id)');
        $this->addSql('CREATE INDEX IDX_DC72E985E934951A ON user_exercise_progress (exercise_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_DC72E985A76ED395E934951A57698A6A ON user_exercise_progress (user_id, exercise_id, role)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_skill_level (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              level VARCHAR(255) NOT NULL,
              achieved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              user_id INT NOT NULL,
              skill_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_16D996BAA76ED395 ON user_skill_level (user_id)');
        $this->addSql('CREATE INDEX IDX_16D996BA5585C142 ON user_skill_level (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_16D996BAA76ED3955585C142 ON user_skill_level (user_id, skill_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              exercise_skill
            ADD
              CONSTRAINT FK_7B0B13B5E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              exercise_skill
            ADD
              CONSTRAINT FK_7B0B13B55585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              exercise_group_item
            ADD
              CONSTRAINT FK_7630A20EFE54D947 FOREIGN KEY (group_id) REFERENCES exercise_group (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              exercise_group_item
            ADD
              CONSTRAINT FK_7630A20EE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              partnership
            ADD
              CONSTRAINT FK_8619D6AE56AE248B FOREIGN KEY (user1_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              partnership
            ADD
              CONSTRAINT FK_8619D6AE441B8B65 FOREIGN KEY (user2_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              partnership_progress
            ADD
              CONSTRAINT FK_DA7ABF1B6AE7F85 FOREIGN KEY (partnership_id) REFERENCES partnership (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              partnership_progress
            ADD
              CONSTRAINT FK_DA7ABF1BE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              session_log
            ADD
              CONSTRAINT FK_F2E6F0FF6AE7F85 FOREIGN KEY (partnership_id) REFERENCES partnership (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_exercise_progress
            ADD
              CONSTRAINT FK_DC72E985A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_exercise_progress
            ADD
              CONSTRAINT FK_DC72E985E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_skill_level
            ADD
              CONSTRAINT FK_16D996BAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              user_skill_level
            ADD
              CONSTRAINT FK_16D996BA5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_skill DROP CONSTRAINT FK_7B0B13B5E934951A');
        $this->addSql('ALTER TABLE exercise_skill DROP CONSTRAINT FK_7B0B13B55585C142');
        $this->addSql('ALTER TABLE exercise_group_item DROP CONSTRAINT FK_7630A20EFE54D947');
        $this->addSql('ALTER TABLE exercise_group_item DROP CONSTRAINT FK_7630A20EE934951A');
        $this->addSql('ALTER TABLE partnership DROP CONSTRAINT FK_8619D6AE56AE248B');
        $this->addSql('ALTER TABLE partnership DROP CONSTRAINT FK_8619D6AE441B8B65');
        $this->addSql('ALTER TABLE partnership_progress DROP CONSTRAINT FK_DA7ABF1B6AE7F85');
        $this->addSql('ALTER TABLE partnership_progress DROP CONSTRAINT FK_DA7ABF1BE934951A');
        $this->addSql('ALTER TABLE session_log DROP CONSTRAINT FK_F2E6F0FF6AE7F85');
        $this->addSql('ALTER TABLE user_exercise_progress DROP CONSTRAINT FK_DC72E985A76ED395');
        $this->addSql('ALTER TABLE user_exercise_progress DROP CONSTRAINT FK_DC72E985E934951A');
        $this->addSql('ALTER TABLE user_skill_level DROP CONSTRAINT FK_16D996BAA76ED395');
        $this->addSql('ALTER TABLE user_skill_level DROP CONSTRAINT FK_16D996BA5585C142');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_skill');
        $this->addSql('DROP TABLE exercise_group');
        $this->addSql('DROP TABLE exercise_group_item');
        $this->addSql('DROP TABLE partnership');
        $this->addSql('DROP TABLE partnership_progress');
        $this->addSql('DROP TABLE session_log');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_exercise_progress');
        $this->addSql('DROP TABLE user_skill_level');
    }
}
